### PR TITLE
Replace camera modell with the skull

### PR DESCRIPTION
**Pull request by sir-marc**

### CODE REVIEW

**Review by StuckiSimon — APPROVED** [review]
Looks good 👍

**Comment by StuckiSimon** [comment]
Could we maybe adjust the position of the skull? Currently it's not nicely visible on my MacBook.

**Comment by sir-marc** [comment]
> Could we maybe adjust the position of the skull? Currently it's not nicely visible on my MacBook.

Did so, but needed to add also some local scales. The algorithm doesnt seem to bother.

**Comment by StuckiSimon** [comment]
Just out of curiosity: what's the implications for the benchmark? Any difference?

**Comment by StuckiSimon** [comment]
> > Could we maybe adjust the position of the skull? Currently it's not nicely visible on my MacBook.
> 
> Did so, but needed to add also some local scales. The algorithm doesnt seem to bother.

No, why should the algorithm bother? The algorithm currently simply ignores what you type in there ✌️

**Comment by sir-marc** [comment]
The gap increased a little:
image

**Pull request merged**
